name: Git Town

on:
  pull_request:
    branches:
      - "**"

jobs:
  git-town:
    name: Display the branch stack
    if: ${{ github.event.pull_request.user.login != 'pr-stacker[bot]' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - uses: git-town/action@v1
